language: node_js
node_js:
- '6'
script: NODE_ENV=test mocha test/index_tests
deploy:
  api_key:
    secure: nszDdv18FuYcaRBsYVYW2QJ0mtRNJUzNTVTGoFRUWRQ0cGmKWY30LBP4+2s3GL16+L4X7h2clASm0mHgRUCL2dcXQrYccqgF5BcqUDVMmroiFvoR3awVgn5vM4hkCcthVH1lVg1FQmjnpbUeFfdQrbObp1T1dR+zJ+I1sweSYp9ZT9qw0RpnWezDWGPb544g7RvTvAZHRn9vu8ZutV8P2ngyXDDf/Ik7M4/8iFExPcCta4UanS4iP3ylFdZGRTfYBmMlOCeV9kBveuVBGkCUnY/9hHgJajVKU10OIWx/O3d0aFEvbrd2Sg9FLp46FxOZrIG6eMl/dLTYqCQ98BPamcyOO0ycM4umnHG1KxiWe4Z7B4rPzaZVG3+2Dan3oI98zqMcVp8oHbyFjN3wwJGkwHetpldbwTRINMqsse/7fcsINnk13w6FiK3UL2LCU9HQi9BsiSiMlbUSNDxZBtpCM9OButGE9BnswTTWG6OzazSLe/+rKteZ9rLPhV9I1Ycx3SAP/0kLIKm3senjw7loJ9o1SJCOULo1ItWcEQXUzYh3keo9AC0HOl0MvtZeDVtTx28dycNH8BrYvMAo+ZH6slllA/J8Q/HnEd9wd3SZGkMYBQaY+4JGQNGfvb4USXMvEvt/TOA6DYeVjfdim/fE+8Q9WmlwVcnyIzvy88eWe9o=
